import type {
  User,
  Course,
  Transaction,
  Enrollment,
  Certificate,
  Notification,
  Analytics,
  Module,
  Review,
} from "./types"

// Mock Users Data
export const mockUsers: User[] = [
  {
    id: "admin-1",
    email: "admin@example.com",
    name: "System Administrator",
    role: "admin",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2024-01-01",
    lastActive: "2024-01-25",
    permissions: ["all"],
    profile: {
      bio: "System administrator with 10+ years of experience in educational technology.",
      location: "San Francisco, CA",
      website: "https://admin.example.com",
      phone: "+1 (555) 123-4567",
      skills: ["System Administration", "Database Management", "Security"],
      experience: "10+ years in EdTech",
      education: "MS Computer Science, Stanford University",
    },
  },
  {
    id: "manager-1",
    email: "manager@example.com",
    name: "Content Manager",
    role: "manager",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2024-01-15",
    lastActive: "2024-01-25",
    permissions: ["create_courses", "edit_courses", "view_analytics"],
    profile: {
      bio: "Experienced educator and course creator specializing in web development.",
      location: "New York, NY",
      website: "https://manager.example.com",
      skills: ["Course Creation", "Web Development", "Teaching"],
      experience: "8 years in online education",
      education: "BS Computer Science, MIT",
    },
    stats: {
      coursesCreated: 12,
      totalRevenue: 45000,
    },
  },
  {
    id: "learner-1",
    email: "learner@example.com",
    name: "John Learner",
    role: "learner",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2024-02-01",
    lastActive: "2024-01-25",
    permissions: ["view_courses", "enroll_courses"],
    profile: {
      bio: "Passionate learner interested in web development and design.",
      location: "Austin, TX",
      skills: ["JavaScript", "React", "CSS"],
      experience: "2 years in web development",
      education: "BS Information Technology",
    },
    stats: {
      coursesEnrolled: 5,
      coursesCompleted: 2,
      totalSpent: 299,
    },
  },
  {
    id: "user-2",
    email: "alice.johnson@email.com",
    name: "Alice Johnson",
    role: "learner",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2024-01-15",
    lastActive: "2024-01-24",
    permissions: ["view_courses", "enroll_courses"],
    stats: {
      coursesEnrolled: 3,
      coursesCompleted: 1,
      totalSpent: 199,
    },
  },
  {
    id: "user-3",
    email: "bob.smith@email.com",
    name: "Bob Smith",
    role: "learner",
    avatar: "/placeholder.svg?height=40&width=40",
    joinDate: "2023-12-10",
    lastActive: "2024-01-23",
    permissions: ["view_courses", "enroll_courses"],
    stats: {
      coursesEnrolled: 4,
      coursesCompleted: 3,
      totalSpent: 397,
    },
  },
]

// Mock Modules and Lessons
const reactModules: Module[] = [
  {
    id: "module-1",
    courseId: "1",
    title: "Getting Started with React",
    description: "Learn the basics of React and set up your development environment",
    order: 1,
    lessons: [
      {
        id: "lesson-1-1",
        moduleId: "module-1",
        title: "What is React?",
        description: "Introduction to React and its core concepts",
        type: "video",
        duration: 15,
        order: 1,
        videoUrl: "https://example.com/video1.mp4",
        isFree: true,
      },
      {
        id: "lesson-1-2",
        moduleId: "module-1",
        title: "Setting up Development Environment",
        description: "Install Node.js, npm, and create your first React app",
        type: "video",
        duration: 20,
        order: 2,
        videoUrl: "https://example.com/video2.mp4",
      },
      {
        id: "lesson-1-3",
        moduleId: "module-1",
        title: "Understanding JSX",
        description: "Learn about JSX syntax and how it works",
        type: "video",
        duration: 18,
        order: 3,
        videoUrl: "https://example.com/video3.mp4",
      },
    ],
  },
  {
    id: "module-2",
    courseId: "1",
    title: "Components and Props",
    description: "Deep dive into React components and how to pass data between them",
    order: 2,
    lessons: [
      {
        id: "lesson-2-1",
        moduleId: "module-2",
        title: "Creating Your First Component",
        description: "Learn how to create and use React components",
        type: "video",
        duration: 25,
        order: 1,
        videoUrl: "https://example.com/video4.mp4",
      },
      {
        id: "lesson-2-2",
        moduleId: "module-2",
        title: "Props and Data Flow",
        description: "Understanding how to pass data between components",
        type: "video",
        duration: 22,
        order: 2,
        videoUrl: "https://example.com/video5.mp4",
      },
      {
        id: "lesson-2-3",
        moduleId: "module-2",
        title: "Component Quiz",
        description: "Test your knowledge of React components",
        type: "quiz",
        duration: 10,
        order: 3,
      },
    ],
  },
]

// Mock Reviews
const mockReviews: Review[] = [
  {
    id: "review-1",
    courseId: "1",
    userId: "learner-1",
    userName: "John Learner",
    userAvatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    comment:
      "Excellent course! The instructor explains concepts clearly and the hands-on projects were really helpful.",
    createdAt: "2024-01-20",
    helpful: 12,
    hasResponse: true,
    response: {
      content: "Thank you for the kind words! I'm glad you found the course helpful.",
      createdAt: "2024-01-21",
    },
  },
  {
    id: "review-2",
    courseId: "1",
    userId: "user-2",
    userName: "Alice Johnson",
    userAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4,
    comment: "Great course content, but I wish there were more practical exercises.",
    createdAt: "2024-01-18",
    helpful: 8,
    hasResponse: false,
  },
]

// Mock Courses Data
export const mockCourses: Course[] = [
  {
    id: "1",
    title: "React.js Fundamentals",
    description:
      "Master the fundamentals of React.js and build modern web applications. This comprehensive course covers everything from basic concepts to advanced patterns, including hooks, context, and state management.",
    shortDescription: "Learn React.js from scratch and build modern web applications",
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: "John Smith",
    instructorId: "manager-1",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Web Development",
    level: "beginner",
    price: 99.99,
    originalPrice: 149.99,
    rating: 4.8,
    reviewCount: 156,
    enrollmentCount: 1234,
    duration: "8 hours",
    lessonsCount: 24,
    language: "English",
    status: "published",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-15",
    tags: ["React", "JavaScript", "Frontend", "Web Development"],
    requirements: [
      "Basic knowledge of HTML and CSS",
      "Understanding of JavaScript fundamentals",
      "A computer with internet connection",
    ],
    whatYouWillLearn: [
      "Build modern React applications from scratch",
      "Understand React components and JSX",
      "Master React hooks and state management",
      "Implement routing with React Router",
      "Connect to APIs and handle data",
      "Deploy React applications to production",
    ],
    modules: reactModules,
    reviews: mockReviews,
  },
  {
    id: "2",
    title: "Advanced JavaScript Concepts",
    description:
      "Deep dive into advanced JavaScript concepts including closures, prototypes, async programming, and modern ES6+ features.",
    shortDescription: "Master advanced JavaScript concepts and patterns",
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: "Jane Doe",
    instructorId: "manager-1",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Programming",
    level: "advanced",
    price: 149.99,
    rating: 4.9,
    reviewCount: 89,
    enrollmentCount: 892,
    duration: "12 hours",
    lessonsCount: 32,
    language: "English",
    status: "published",
    createdAt: "2024-01-05",
    updatedAt: "2024-01-20",
    tags: ["JavaScript", "Advanced", "Programming", "ES6"],
    requirements: [
      "Solid understanding of JavaScript basics",
      "Experience with functions and objects",
      "Familiarity with web development",
    ],
    whatYouWillLearn: [
      "Master closures and scope",
      "Understand prototypal inheritance",
      "Work with async/await and Promises",
      "Use advanced array methods",
      "Implement design patterns",
      "Optimize JavaScript performance",
    ],
    modules: [],
    reviews: [],
  },
  {
    id: "3",
    title: "UI/UX Design Fundamentals",
    description:
      "Learn the principles of user interface and user experience design. Create beautiful and functional designs.",
    shortDescription: "Master UI/UX design principles and create stunning interfaces",
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: "Mike Johnson",
    instructorId: "manager-1",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Design",
    level: "intermediate",
    price: 79.99,
    rating: 4.6,
    reviewCount: 67,
    enrollmentCount: 189,
    duration: "6 hours",
    lessonsCount: 18,
    language: "English",
    status: "published",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-12",
    tags: ["UI", "UX", "Design", "Figma"],
    requirements: ["Basic computer skills", "Interest in design", "Figma account (free)"],
    whatYouWillLearn: [
      "Understand design principles",
      "Create user personas and journeys",
      "Design wireframes and prototypes",
      "Use Figma effectively",
      "Conduct user research",
      "Test and iterate designs",
    ],
    modules: [],
    reviews: [],
  },
  {
    id: "4",
    title: "Node.js Backend Development",
    description:
      "Build scalable backend applications with Node.js, Express, and MongoDB. Learn API development and database integration.",
    shortDescription: "Build powerful backend applications with Node.js",
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: "Sarah Wilson",
    instructorId: "manager-1",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Backend",
    level: "intermediate",
    price: 199.99,
    rating: 4.7,
    reviewCount: 234,
    enrollmentCount: 567,
    duration: "15 hours",
    lessonsCount: 40,
    language: "English",
    status: "published",
    createdAt: "2024-01-08",
    updatedAt: "2024-01-18",
    tags: ["Node.js", "Express", "MongoDB", "API"],
    requirements: [
      "JavaScript fundamentals",
      "Basic understanding of web development",
      "Node.js installed on computer",
    ],
    whatYouWillLearn: [
      "Build REST APIs with Express",
      "Work with MongoDB and Mongoose",
      "Implement authentication and authorization",
      "Handle file uploads and processing",
      "Deploy applications to cloud platforms",
      "Test APIs with Jest and Supertest",
    ],
    modules: [],
    reviews: [],
  },
  {
    id: "5",
    title: "Python for Data Science",
    description:
      "Learn Python programming for data analysis, visualization, and machine learning. Perfect for beginners.",
    shortDescription: "Master Python for data science and analytics",
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: "Dr. Emily Chen",
    instructorId: "manager-1",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Data Science",
    level: "beginner",
    price: 129.99,
    rating: 4.5,
    reviewCount: 178,
    enrollmentCount: 445,
    duration: "10 hours",
    lessonsCount: 28,
    language: "English",
    status: "published",
    createdAt: "2024-01-12",
    updatedAt: "2024-01-22",
    tags: ["Python", "Data Science", "Analytics", "Machine Learning"],
    requirements: ["No programming experience required", "Basic math knowledge", "Computer with Python installed"],
    whatYouWillLearn: [
      "Python programming fundamentals",
      "Data manipulation with Pandas",
      "Data visualization with Matplotlib",
      "Statistical analysis techniques",
      "Introduction to machine learning",
      "Work with real datasets",
    ],
    modules: [],
    reviews: [],
  },
  {
    id: "6",
    title: "Mobile App Development with Flutter",
    description: "Create beautiful cross-platform mobile applications using Flutter and Dart programming language.",
    shortDescription: "Build cross-platform mobile apps with Flutter",
    thumbnail: "/placeholder.svg?height=200&width=300",
    instructor: "Alex Rodriguez",
    instructorId: "manager-1",
    instructorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Mobile Development",
    level: "intermediate",
    price: 179.99,
    rating: 4.4,
    reviewCount: 92,
    enrollmentCount: 234,
    duration: "14 hours",
    lessonsCount: 35,
    language: "English",
    status: "published",
    createdAt: "2024-01-14",
    updatedAt: "2024-01-24",
    tags: ["Flutter", "Dart", "Mobile", "Cross-platform"],
    requirements: [
      "Basic programming knowledge",
      "Understanding of object-oriented programming",
      "Flutter SDK installed",
    ],
    whatYouWillLearn: [
      "Flutter framework fundamentals",
      "Dart programming language",
      "Building responsive UIs",
      "State management with Provider",
      "API integration and data handling",
      "Publishing apps to app stores",
    ],
    modules: [],
    reviews: [],
  },
]

// Mock Transactions Data
export const mockTransactions: Transaction[] = [
  {
    id: "TXN-001",
    userId: "learner-1",
    userName: "John Learner",
    userEmail: "learner@example.com",
    type: "course_purchase",
    amount: 99.99,
    currency: "USD",
    status: "completed",
    paymentMethod: "credit_card",
    courseId: "1",
    courseName: "React.js Fundamentals",
    createdAt: "2024-01-20T10:30:00Z",
    completedAt: "2024-01-20T10:30:15Z",
    paymentGateway: "stripe",
    transactionFee: 3.2,
    netAmount: 96.79,
    refundable: true,
  },
  {
    id: "TXN-002",
    userId: "user-2",
    userName: "Alice Johnson",
    userEmail: "alice.johnson@email.com",
    type: "course_purchase",
    amount: 149.99,
    currency: "USD",
    status: "completed",
    paymentMethod: "paypal",
    courseId: "2",
    courseName: "Advanced JavaScript",
    createdAt: "2024-01-19T11:15:00Z",
    completedAt: "2024-01-19T11:15:30Z",
    paymentGateway: "paypal",
    transactionFee: 4.5,
    netAmount: 145.49,
    refundable: true,
  },
  {
    id: "TXN-003",
    userId: "user-3",
    userName: "Bob Smith",
    userEmail: "bob.smith@email.com",
    type: "refund",
    amount: -79.99,
    currency: "USD",
    status: "completed",
    paymentMethod: "credit_card",
    courseId: "3",
    courseName: "UI/UX Design Fundamentals",
    createdAt: "2024-01-18T14:20:00Z",
    completedAt: "2024-01-18T14:25:00Z",
    paymentGateway: "stripe",
    transactionFee: -2.4,
    netAmount: -77.59,
    refundable: false,
    originalTransactionId: "TXN-000",
    refundReason: "Customer requested refund",
  },
]

// Mock Enrollments Data
export const mockEnrollments: Enrollment[] = [
  {
    id: "enroll-1",
    userId: "learner-1",
    courseId: "1",
    enrolledAt: "2024-01-20T10:30:00Z",
    progress: 65,
    completedLessons: ["lesson-1-1", "lesson-1-2", "lesson-2-1"],
    lastAccessedAt: "2024-01-25T09:15:00Z",
  },
  {
    id: "enroll-2",
    userId: "learner-1",
    courseId: "2",
    enrolledAt: "2024-01-15T14:20:00Z",
    progress: 30,
    completedLessons: ["lesson-1-1"],
    lastAccessedAt: "2024-01-24T16:30:00Z",
  },
  {
    id: "enroll-3",
    userId: "user-2",
    courseId: "1",
    enrolledAt: "2024-01-18T12:00:00Z",
    progress: 100,
    completedLessons: ["lesson-1-1", "lesson-1-2", "lesson-1-3", "lesson-2-1", "lesson-2-2", "lesson-2-3"],
    lastAccessedAt: "2024-01-23T11:45:00Z",
    completedAt: "2024-01-23T11:45:00Z",
    certificateId: "cert-1",
  },
]

// Mock Certificates Data
export const mockCertificates: Certificate[] = [
  {
    id: "cert-1",
    userId: "user-2",
    courseId: "1",
    courseName: "React.js Fundamentals",
    instructor: "John Smith",
    completedAt: "2024-01-23T11:45:00Z",
    issuedAt: "2024-01-23T12:00:00Z",
  },
]

// Mock Notifications Data
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "learner-1",
    type: "course_update",
    title: "New lesson added to React.js Fundamentals",
    message: 'A new lesson "Advanced Hooks" has been added to your enrolled course.',
    isRead: false,
    createdAt: "2024-01-25T10:00:00Z",
    actionUrl: "/learn/1",
  },
  {
    id: "notif-2",
    userId: "learner-1",
    type: "achievement",
    title: "Congratulations! Course completed",
    message: 'You have successfully completed "JavaScript Essentials". Your certificate is ready!',
    isRead: true,
    createdAt: "2024-01-24T15:30:00Z",
    actionUrl: "/dashboard",
  },
  {
    id: "notif-3",
    userId: "learner-1",
    type: "new_course",
    title: "New course recommendation",
    message: 'Based on your interests, we recommend "Advanced React Patterns".',
    isRead: false,
    createdAt: "2024-01-23T09:00:00Z",
    actionUrl: "/courses/7",
  },
]

// Mock Analytics Data
export const mockAnalytics: Analytics = {
  overview: {
    totalUsers: 15420,
    totalCourses: 156,
    totalRevenue: 234567,
    totalEnrollments: 8934,
    activeUsers: 3456,
    newUsersThisMonth: 567,
    revenueThisMonth: 23456,
    enrollmentsThisMonth: 1234,
  },
  userGrowth: [
    { date: "2024-01-01", users: 14000, newUsers: 120 },
    { date: "2024-01-02", users: 14120, newUsers: 95 },
    { date: "2024-01-03", users: 14215, newUsers: 110 },
    { date: "2024-01-04", users: 14325, newUsers: 87 },
    { date: "2024-01-05", users: 14412, newUsers: 134 },
    { date: "2024-01-06", users: 14546, newUsers: 156 },
    { date: "2024-01-07", users: 14702, newUsers: 98 },
  ],
  revenueData: [
    { date: "2024-01-01", revenue: 1200, transactions: 12 },
    { date: "2024-01-02", revenue: 980, transactions: 8 },
    { date: "2024-01-03", revenue: 1450, transactions: 15 },
    { date: "2024-01-04", revenue: 890, transactions: 7 },
    { date: "2024-01-05", revenue: 1680, transactions: 18 },
    { date: "2024-01-06", revenue: 2100, transactions: 22 },
    { date: "2024-01-07", revenue: 1340, transactions: 14 },
  ],
  popularCourses: [
    { courseId: "1", title: "React.js Fundamentals", enrollments: 1234, revenue: 123400 },
    { courseId: "2", title: "Advanced JavaScript", enrollments: 892, revenue: 133708 },
    { courseId: "4", title: "Node.js Backend Development", enrollments: 567, revenue: 113433 },
    { courseId: "5", title: "Python for Data Science", enrollments: 445, revenue: 57855 },
    { courseId: "6", title: "Mobile App Development with Flutter", enrollments: 234, revenue: 42126 },
  ],
  categoryStats: [
    { category: "Web Development", courses: 45, enrollments: 3456, revenue: 345600 },
    { category: "Programming", courses: 38, enrollments: 2890, revenue: 289000 },
    { category: "Data Science", courses: 25, enrollments: 1567, revenue: 203710 },
    { category: "Design", courses: 22, enrollments: 1234, revenue: 98720 },
    { category: "Mobile Development", courses: 15, enrollments: 890, revenue: 160200 },
    { category: "Backend", courses: 11, enrollments: 567, revenue: 113400 },
  ],
}
